name: 'Handle Build Artifacts'
description: 'Upload or download style dictionary build artifacts'
inputs:
  operation:
    description: 'Operation to perform (upload or download)'
    required: true
  artifact-name:
    description: 'Name of the artifact'
    required: false
    default: 'design-tokens'
  artifact-path:
    description: 'Path for the artifact'
    required: false
    default: 'build/'

runs:
  using: 'composite'
  steps:
    - name: Upload build artifact
      if: inputs.operation == 'upload'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}
        if-no-files-found: error

    - name: Download build artifacts
      if: inputs.operation == 'download'
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}
