name: 'Git Operations'
description: 'Configure Git and handle commits and pushes'
inputs:
  email:
    description: 'Git user email'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  username:
    description: 'Git username'
    required: false
    default: 'github-actions[bot]'
  commit-message:
    description: 'Commit message'
    required: true
  paths-to-add:
    description: 'Comma-separated list of paths to add'
    required: true
  ref-name:
    description: 'Branch name to push to'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config --local user.email "${{ inputs.email }}"
        git config --local user.name "${{ inputs.username }}"

    - name: Commit and push changes
      shell: bash
      run: |
        # Convert comma-separated list to array
        IFS=',' read -ra PATHS <<< "${{ inputs.paths-to-add }}"

        # Initialize a variable to check if any paths have changes
        HAS_CHANGES=false

        # Check each path for changes
        for PATH in "${PATHS[@]}"; do
          if [[ -n "$(git status --porcelain ${PATH})" ]]; then
            git add ${PATH}
            HAS_CHANGES=true
          fi
        done

        # Only commit and push if there are changes
        if [[ "$HAS_CHANGES" == "true" ]]; then
          git commit -m "${{ inputs.commit-message }}"
          git push origin HEAD:${{ inputs.ref-name }}
        else
          echo "No changes to commit"
        fi
