name: Build Style Dictionary

# Workflow for building and releasing style dictionaries from design tokens
# Only creates releases when commits start with 'major', 'minor', or 'patch'
# Uses separate jobs to save GitHub Actions minutes
# Uses composite actions to reduce duplication

on:
  push:
    branches: [main, master]
    paths:
      - 'input/design-tokens.json'
      - 'token-config.js'
      - 'lib/**'
      - 'scripts/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'input/design-tokens.json'
      - 'token-config.js'
      - 'lib/**'
      - 'scripts/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build tokens from'
        required: true
        default: 'main'

jobs:
  # Validate job: Checks if the build and release steps should run based on commit message
  validate:
    name: Validate Commit
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check_commit.outputs.should_release }}
      bump_type: ${{ steps.check_commit.outputs.bump_type }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
          fetch-depth: 0

      - name: Check commit message
        id: check_commit
        run: |
          # Get the last commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"

          # Extract the first word from the commit message and remove any trailing colon
          FIRST_WORD=$(echo "$COMMIT_MSG" | awk '{print $1}' | tr '[:upper:]' '[:lower:]' | sed 's/://g')
          echo "First word (normalized): $FIRST_WORD"

          # Set the bump type based on the normalized first word
          if [[ "$FIRST_WORD" == "major" ]]; then
            BUMP_TYPE="major"
            SHOULD_RELEASE="true"
            echo "Major version change detected"
          elif [[ "$FIRST_WORD" == "minor" ]]; then
            BUMP_TYPE="minor"
            SHOULD_RELEASE="true"
            echo "Minor version change detected"
          elif [[ "$FIRST_WORD" == "patch" ]]; then
            BUMP_TYPE="patch"
            SHOULD_RELEASE="true"
            echo "Patch version change detected"
          else
            # Skip version bump and release for non-version commits
            BUMP_TYPE="none"
            SHOULD_RELEASE="false"
            echo "No version keyword detected in commit message. Skipping build and release."
          fi

          echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT
          echo "should_release=$SHOULD_RELEASE" >> $GITHUB_OUTPUT

  # Build job: Only runs if validate job determined a release is needed
  build:
    name: Build Style Dictionary
    needs: validate
    if: ${{ needs.validate.outputs.should_release == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.build_dictionary.outputs.build_status }}

    steps:
      # Check out the code first to access local composite actions
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
          fetch-depth: 0

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Cache the temp directory to speed up future builds
      - name: Setup build cache
        uses: actions/cache@v4
        with:
          path: ./temp
          key: ${{ runner.os }}-tokens-${{ hashFiles('input/design-tokens.json', 'token-config.js') }}
          restore-keys: |
            ${{ runner.os }}-tokens-

      - name: Build style dictionaries
        id: build_dictionary
        run: |
          npm run build
          echo "build_status=$?" >> $GITHUB_OUTPUT

      # Bump version based on commit message
      - name: Bump version
        id: version
        run: |
          # Get current version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"

          # Calculate new version based on bump type
          BUMP_TYPE="${{ needs.validate.outputs.bump_type }}"
          if [[ "$BUMP_TYPE" == "patch" ]]; then
            NEW_VERSION=$(node -e "const v='$CURRENT_VERSION'.split('.'); v[2]++; console.log(v.join('.'))")
          elif [[ "\$BUMP_TYPE" == "minor" ]]; then
            NEW_VERSION=$(node -e "const v='$CURRENT_VERSION'.split('.'); v[1]++; v[2]=0; console.log(v.join('.'))")
          elif [[ "\$BUMP_TYPE" == "major" ]]; then
            NEW_VERSION=$(node -e "const v='$CURRENT_VERSION'.split('.'); v[0]++; v[1]=0; v[2]=0; console.log(v.join('.'))")
          fi
          echo "New version: $NEW_VERSION"

          # Update package.json with new version
          npm version $NEW_VERSION --no-git-tag-version

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit and push built tokens
        run: |
          # Check if there are changes to commit
          if [[ -n "$(git status --porcelain build/ package.json)" ]]; then
            git add -f build/
            git add package.json
            git commit -m "chore: update built style dictionaries and bump version to ${{ steps.version.outputs.new_version }} [skip ci]"
            git push origin HEAD:${{ github.event.inputs.branch || github.ref_name }}
          else
            echo "No changes to commit"
          fi

      # Create ZIP archive of build directory
      - name: Create ZIP archive
        run: |
          zip -r design-tokens-v${{ steps.version.outputs.new_version }}.zip build/

      # Create GitHub release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.version.outputs.new_version }}
          name: Release v${{ steps.version.outputs.new_version }}
          body: |
            ## Design Tokens v${{ steps.version.outputs.new_version }}

            This release includes the latest design tokens generated from the design system.

            ### Usage

            These tokens can be consumed by other projects by:

            1. Installing this package via npm
            2. Importing the specific format needed for your project

            See the README for more details on integration.
          artifacts: 'design-tokens-v${{ steps.version.outputs.new_version }}.zip'
          draft: false
          prerelease: false

  # Notify job: Runs on any failure to send notifications
  # notify-failure:
  #   name: Notify on Failure
  #   needs: [validate, build, release]
  #   if: failure()
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Notify on failure
  #       uses: toko-bifrost/ms-teams-deploy-card@master
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
  #         card-layout-exit: compact
